# Generated by Django 5.2.10 on 2026-01-10 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="category",
            field=models.CharField(default="Health", max_length=50),
        ),
        migrations.AlterField(
            model_name="habit",
            name="unit",
            field=models.CharField(
                help_text="Unit of measurement (e.g. hours, ml, pages)",
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="Unit cannot be empty."
                    ),
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z\\s/%]+$",
                        message="Unit must contain only letters, spaces, or symbols like / and %.",
                    ),
                ],
            ),
        ),
    ]
